### ISSUE TITLE
What is a "Data variable"?

### ISSUE THREAD

**Issue by korenmiklos** [gabors-data-analysis/da-coding-rstats#1]
https://github.com/gabors-data-analysis/da-coding-rstats/blob/7b7d6b6159220da959d4ba71ae8775a108293b95/lecture03-tibbles/raw_codes/intro_to_tibbles.R#L25

A variable is a name that is associated with some value, no? This is more like a type. Or does R call types variables? Maybe use "type of variable" if you don't want to introduce the concept of types?

**Comment by regulyagoston** [comment]
Fair point, thanks! Renamed to 'type of variable'.
