### ISSUE TITLE
inconsistent data source

### ISSUE THREAD

**Issue by adamvig96** [gabors-data-analysis/da-coding-rstats#10]
In the [ggplot class,](https://github.com/gabors-data-analysis/da-coding-rstats/blob/d9773a2d3b3eb410751ed8b03bc3ebde74652069/lecture07-ggplot-indepth/complete_codes/ggplot_indepth_fin.R) you used only the Vienna data to create the histogram object (line 113), but later you calculated statistics on the whole sample frame that also contained London hotels when annotating (eg. line 152) which creates inconsistencies.

**Comment by gbekes** [comment]
Let us stick w Vienna, I guess.

**Comment by regulyagoston** [comment]
Corrected, thanks!
