### ISSUE TITLE
Old links for read data

### ISSUE THREAD

**Issue by adamvig96** [gabors-data-analysis/da-coding-rstats#13]
Left the old links when reading data for Part III case studies

eg. 

https://github.com/gabors-data-analysis/da-coding-rstats/blob/6c352ab8f00b43580a2aa247e7228999e3426d1e/lecture25-classification-wML/codes/classification_wML.R#L87

https://github.com/gabors-data-analysis/da-coding-rstats/blob/6c352ab8f00b43580a2aa247e7228999e3426d1e/lecture24-random-forest/codes/randomforest_airbnb.R#L70

**Comment by DanielBarabas** [comment]
Done
