### ISSUE TITLE
incorrect url to download data in 

### ISSUE THREAD

**Issue by Lulliter** [gabors-data-analysis/da-coding-rstats#14]
I am enjoying this great book! 

In the code for the Lasso airbnb case (https://github.com/gabors-data-analysis/da-coding-rstats/blob/main/lecture22-lasso/codes/lasso_aribnb.R) the url to download the data is wrong:
 
it is `url_data <- 'https://raw.githubusercontent.com/gabors-data-analysis/da-coding-rstats/main/partIII-case-studies/case2-airbnb-lasso/data/airbnb_hackney_workfile_adj_book1.csv'`

but should be 
`url_data <- 'https://raw.githubusercontent.com/gabors-data-analysis/da-coding-rstats/refs/heads/main/lecture22-lasso/data/airbnb_hackney_workfile_adj_book1.csv'`

**Comment by gbekes** [comment]
Thanks. 
Thanks, please keep them coming, @DanielBarabas is doing a code review in terms of links etc.

**Comment by DanielBarabas** [comment]
Thanks @Lulliter, it is fixed now
