### ISSUE TITLE
Remove whitespace from function calls

### ISSUE THREAD

**Issue by korenmiklos** [gabors-data-analysis/da-coding-rstats#3]
https://github.com/gabors-data-analysis/da-coding-rstats/blob/7b7d6b6159220da959d4ba71ae8775a108293b95/lecture03-tibbles/raw_codes/intro_to_tibbles.R#L306

What is the style guide for R? In Python, whitespace is not used in function calls, except after commas.

`reduce(x, dims=1, map=sum)` 

rather than 

`reduce( x , dims = 1, map = sum)` 

Consider using an automatic linter to adopt a consistent code style

**Comment by daroczig** [comment]
Yeah, leading/trailing spaces inside of parens look odd, although space after (but NOT before) comma is pretty standard. I'd write the above as:

```r
fj <- full_join(games, points , by = c('team', 'manager_id', 'manager_name')) 
```

The standard linter for R: https://github.com/r-lib/lintr

If going with `tidyverse` already, maybe use their style guide as well: https://style.tidyverse.org/

**Comment by divenyijanos** [comment]
Standardize quotation marks as well: choose `'` or `"` and use them everywhere.
See e.g. here: https://github.com/gabors-data-analysis/da-coding-rstats/blob/main/lecture08-conditionals/conditionals.md#multiple-if-and-else-statements

**Comment by regulyagoston** [comment]
Great points, thanks will standardize these issues and check the spacing everywhere (I was not careful enough)

**Comment by daroczig** [comment]
There's still whitespace after the staring paren and before the closing parent -- this looks pretty odd to me, and not sure if any R code style is suggesting that :zipper_mouth_face:

**Comment by regulyagoston** [comment]
Thanks, @daroczig! It is always a pleasure to learn something new/better even if it means I have to 're-learn' this spacing part and force myself to this new format! :) Any other comments are welcome!
