### ISSUE TITLE
Don't eval online scripts

### ISSUE THREAD

**Issue by daroczig** [gabors-data-analysis/da-coding-rstats#4]
There are a few examples of calling `source_url` (BTW what is the advantage over `source` if not providing the `hash` param), which IMO is a dangerous practice -- someone might place malicious code on the Internet (even in this repo after getting access to the repo either via credential leakage, misconfiguration of access controls, or GH bug etc), and running those without first at least checking manually what is to be run, might result in serious security issues.

See e.g. https://github.com/daroczig/CEU-DV2/blob/18b927e894f3b506e78514c3553b68cd7e37f5b6/1.R#L5 and then https://github.com/daroczig/CEU-DV2/blob/18b927e894f3b506e78514c3553b68cd7e37f5b6/1.R#L43.

Maybe package up your helpers into an R package and publish on CRAN? That is much less likely to change/hijack over time.

**Comment by regulyagoston** [comment]
Hmm, never thought about these issues... thanks for raising my attention. Will think it through and find a better solution than `source_url`...

**Comment by regulyagoston** [comment]
Finally, I have used `source()` when needed except in one place where the `theme_bg()` is called ([lecture07-ggplot-indepth](https://github.com/gabors-data-analysis/da-coding-rstats/tree/main/lecture07-ggplot-indepth). Here, we take the risks at this stage, and in the future want to create a package or something similar.
