### ISSUE TITLE
deprecated dplyr/tidyverse functions

### ISSUE THREAD

**Issue by daroczig** [gabors-data-analysis/da-coding-rstats#5]
I am not suggesting switching to packages with less frequently changing APIs :) But you will need to keep up with the updates, see e.g. `sample_n` has been superseded by `slice_sample` -- at least based on a quick search. Please check the changelog at least for the major releases since the scripts were originally written, as there might be other changes as well.

**Comment by regulyagoston** [comment]
Yes, I should reopen this issue, I have been aware that `sample_n` was superseded, but decided to use it rather as it seemed to be easier to use. 
Anyways will change it to `slice_sampe`! Thanks for pointing it out!

**Comment by regulyagoston** [comment]
`sample_n` is now replaced with `slice_sample`.
