### ISSUE TITLE
Change `myString` to more meaningful variable name

### ISSUE THREAD

**Issue by korenmiklos** [gabors-data-analysis/da-coding-rstats#7]
https://github.com/gabors-data-analysis/da-coding-rstats/blob/587cd1eb4e718faf6fc522744c9bb04138fc6add/lecture01-coding-basics/coding_basics.Rmd#L50

Neither `my` nor `String` are very informative. Moreover, camelCase is [not the preferred style](https://style.tidyverse.org/syntax.html#object-names). Consider using `message` instead.

**Comment by regulyagoston** [comment]
Thanks! I have used `message_world` as it is more useful to show (bad) alternatives as well as the `message` is a built-in function and wanted to avoid redefining existing functions.
