### ISSUE TITLE
Do not call for short variable names

### ISSUE THREAD

**Issue by korenmiklos** [gabors-data-analysis/da-coding-rstats#8]
https://github.com/gabors-data-analysis/da-coding-rstats/blob/587cd1eb4e718faf6fc522744c9bb04138fc6add/lecture01-coding-basics/coding_basics.Rmd#L77

The first couple of examples of short variable names are not informative. Even the unnecessarily wordy long variable name is more helpful. With all IDEs supporting tab completion, I do not see a real need for short names. For example, `user_message` is always clearer than `umsg`.

**Comment by gbekes** [comment]
I agree. we shall avoid `umsg` in favor of `user_message˙`
My recollection is that I mostly tried in original code, although maybe not all cases.

**Comment by regulyagoston** [comment]
Removed from the list.
